### PR TITLE
Remove components to separate apps

### PR DESCRIPTION
**Pull request by brenoc**
Split Banner and Shelf into a separate app:
- https://github.com/vtex-apps/storefront-banner
- https://github.com/vtex-apps/storefront-shelf

### CODE REVIEW

**Comment by brenoc** [comment]
Oh! Also I added Price and Img components to SDK (https://github.com/vtex-apps/storefront-sdk/pull/25) so other apps may use the same component.

**Comment by tamorim** [comment]
Nice! I think we should separate more stuff!
One "bad" thing is having to use the toolbelt to listen everything if you want to work on the page... in the end will have a LOT of tabs. Is there a way to ease this process?

I don't think it's difficult, but, shouldn't be easier to render a component?

**Comment by brenoc** [comment]
@tamorim we should publish a version o storefront-theme, storefront-banner and storefront-shelf and keep the last two in the meta.json dependencies of storefront-theme.

Example:
Storefront Theme is installed, Storefront Banner and Storefront Shelf are installed as well, because they are Storefront Theme dependencies. 

If you add Storefront Theme to your sandbox, it will only sandbox Storefront Theme, but it will get Storefront Banner and Storefront Shelf from Gallery.

**Comment by tamorim** [comment]
Ohh, nice :)

**Pull request merged**
